### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by pnappa** [Hurricane996/Hackertyper#3]
Hi, saw your post from proggit!

Just wanted to put a pointer out there that you should include some kind of sequences of commands that should be run to get it up and running.

I think, at least from my quick attempt, is that you only need to run the following commands:

```
autoreconf
automake --add-missing
./configure
make
```

Then of course, the built executable should be in `./src/`.

Also, you appear to have a dangling link in the repo - you should remove that symlink called INSTALL from the root dir, it's an artifact from autoconf.

Hopefully this helped :)

**Comment by hyasynthesized** [comment]
I rewrote the entire thing completely. I no longer use autohell, which should make things a lot clearer.
